from engine.checks import (
    # Policy checks
    check_app_any,
    check_service_any,
    check_zone_any,
    check_log_end,

    # Security profile checks
    check_missing_av_profile,
    check_missing_as_profile,
    check_missing_vp_profile,

    # CIS device management checks
    check_mgmt_http_telnet_disabled,
    check_mgmt_profile_http_telnet_disabled,
    check_mgmt_interface_permitted_ips,
    check_admin_profiles_on_dp_interfaces,
    check_login_banner_dod,
    check_login_banner_set,
    check_admin_lockout_failed_attempts_3,
    check_only_one_local_admin,
    check_mgmt_ssl_tls_certificate_set,
    check_manual,

    # CIS password checks
    check_password_complexity_enabled,
    check_password_min_length_12,
    check_password_min_length_15,

    # CIS device services checks
    check_ntp_redundant_servers,
    check_timezone_utc_gmt,
    check_ntp_authentication_enabled,

    # CIS logging checks
    check_syslog_configured,
    check_syslog_hostname_or_fqdn,
    check_admin_lockout_requires_release,
    check_snmpv3_traps_configured,
    check_log_high_dp_load_enabled,
    check_alarms_enabled,
    check_audit_storage_alarms_75,
    check_packet_buffer_protection_enabled,
    check_log_forwarding_threat_auth,
    check_zone_protection_syn_cookies,
    check_zone_protection_flood_enabled,
    check_zone_protection_recon_enabled,
    check_zone_protection_drop_special,

    # CIS user-id checks
    check_ip_user_mapping_configured,
    check_wmi_probing_disabled,
    check_user_id_only_on_trusted,
    check_user_id_include_exclude_configured,

    # CIS authentication settings checks
    check_idle_timeout_max_10,
    check_auth_profile_lockout_configured,

    # CIS SNMP polling checks
    check_snmp_polling_v3,
    check_snmp_v1_v2_disabled,

    # CIS update server identity
    check_verify_update_server_identity,

    # CIS password complexity checks
    check_password_min_uppercase_1,
    check_password_min_lowercase_1,
    check_password_min_numeric_1,
    check_password_min_special_1,
    check_password_change_period_max_90,
    check_password_differs_3,
    check_password_differs_8,
    check_password_reuse_24,
    check_password_profiles_absent,

    # CIS VPN checks (manual)
    check_ikev2_post_quantum_enabled,

    # CIS high availability checks
    check_ha_peer_configured,
    check_ha_link_or_path_monitoring,
    check_ha_passive_link_state_preemptive,

    # CIS dynamic updates
    check_antivirus_updates_hourly,
    check_threats_updates_daily_or_better,

    # CIS wildfire checks
    check_wildfire_file_size_limits,
    check_wildfire_analysis_on_rules,
    check_wildfire_forward_decrypted_content,
    check_wildfire_session_info_settings,
    check_wildfire_alerts_enabled,
    check_wildfire_update_realtime,
    check_wildfire_public_cloud_region,
    check_wildfire_inline_cloud_analysis,

    # CIS threat prevention checks
    check_av_reset_both_decoders,
    check_spyware_blocks_all_severities,
    check_spyware_dns_sinkhole,
    check_vp_blocks_critical_high,
    check_url_filtering_on_rules,
    check_url_filtering_block_override_categories,
    check_url_filtering_no_allow_categories,
    check_url_http_header_logging,
    check_vp_inline_cloud_analysis,
    check_url_cloud_inline_categorization,
    check_spyware_inline_cloud_analysis,

    # CIS security policy checks
    check_app_specific_untrusted_to_trusted,
    check_malicious_ip_deny_rules,
    check_default_policy_logging,
)

CONTROL_REGISTRY = [
    {
        "id": "PANW-BP-POL-APP-ANY",
        "display_id": "PANW BP • Policy",
        "title": "Application Any Used in Allow Rule",
        "category": "Security Policy",
        "severity": "High",
        "framework": "PANW",
        "section": "Best Practice - Security Policy",
        "cis_level": 1,
        "recommendation": "Restrict rules to specific applications using App-ID.",
        "check": check_app_any,
        "scope": "rules",
    },
    {
        "id": "PANW-BP-POL-SVC-ANY",
        "display_id": "PANW BP • Policy",
        "title": "Service Any Used in Allow Rule",
        "category": "Security Policy",
        "severity": "High",
        "framework": "PANW",
        "section": "Best Practice - Security Policy",
        "cis_level": 1,
        "recommendation": "Restrict services to required ports and protocols.",
        "check": check_service_any,
        "scope": "rules",
    },
    {
        "id": "PANW-BP-POL-ZONE-ANY",
        "display_id": "PANW BP • Policy",
        "title": "Any Zone Used in Allow Rule",
        "category": "Security Policy",
        "severity": "Medium",
        "framework": "PANW",
        "section": "Best Practice - Security Policy",
        "cis_level": 1,
        "recommendation": "Explicitly define source and destination zones in security rules.",
        "check": check_zone_any,
        "scope": "rules",
    },
    {
        "id": "PANW-BP-POL-LOG-END",
        "display_id": "PANW BP • Policy",
        "title": "Log at Session End Not Enabled",
        "category": "Security Policy",
        "severity": "Medium",
        "framework": "PANW",
        "section": "Best Practice - Security Policy",
        "cis_level": 1,
        "recommendation": "Enable logging at session end for all allow rules.",
        "check": check_log_end,
        "scope": "rules",
    },
    {
        "id": "PANW-BP-POL-NO-AV",
        "display_id": "PANW BP • Security Profiles",
        "title": "Missing Anti-Virus Profile",
        "category": "Security Profiles",
        "severity": "High",
        "framework": "PANW",
        "section": "Best Practice - Security Profiles",
        "cis_level": 1,
        "recommendation": "Apply an Anti-Virus security profile to all allow rules.",
        "check": check_missing_av_profile,
        "scope": "rules",
    },
    {
        "id": "PANW-BP-POL-NO-AS",
        "display_id": "PANW BP • Security Profiles",
        "title": "Missing Anti-Spyware Profile",
        "category": "Security Profiles",
        "severity": "High",
        "framework": "PANW",
        "section": "Best Practice - Security Profiles",
        "cis_level": 1,
        "recommendation": "Apply an Anti-Spyware security profile to all allow rules.",
        "check": check_missing_as_profile,
        "scope": "rules",
    },
    {
        "id": "PANW-BP-POL-NO-VP",
        "display_id": "PANW BP • Security Profiles",
        "title": "Missing Vulnerability Protection Profile",
        "category": "Security Profiles",
        "severity": "High",
        "framework": "PANW",
        "section": "Best Practice - Security Profiles",
        "cis_level": 1,
        "recommendation": "Apply a Vulnerability Protection profile to all allow rules.",
        "check": check_missing_vp_profile,
        "scope": "rules",
    },
    {
        "id": "PANW-BP-MGMT-PERMITTED-IP",
        "display_id": "PANW BP • Admin Access",
        "title": "Management Interface Permitted IPs Configured",
        "category": "Administrative Access",
        "severity": "Medium",
        "framework": "PANW",
        "frameworks": ["PANW", "CIS"],
        "section": "Best Practice - Administrative Access",
        "cis_level": 1,
        "recommendation": "Restrict management access to permitted IP addresses.",
        "check": check_mgmt_interface_permitted_ips,
    },
    {
        "id": "PANW-BP-MGMT-DP-PROFILES",
        "display_id": "PANW BP • Admin Access",
        "title": "Management Profiles Assigned to Data Plane Interfaces",
        "category": "Administrative Access",
        "severity": "Low",
        "framework": "PANW",
        "section": "Best Practice - Administrative Access",
        "cis_level": 1,
        "recommendation": (
            "Avoid management profiles on data plane interfaces; "
            "disable HTTP/Telnet if required."
        ),
        "check": check_admin_profiles_on_dp_interfaces,
    },
    {
        "id": "PANW-BP-SESSION-PACKET-BUFFER",
        "display_id": "PANW BP • Session",
        "title": "Packet Buffer Protection Enabled",
        "category": "Session Settings",
        "severity": "Medium",
        "framework": "PANW",
        "section": "Best Practice - Session Settings",
        "cis_level": 1,
        "recommendation": (
            "Enable packet buffer protection and configure latency thresholds."
        ),
        "check": check_packet_buffer_protection_enabled,
    },
    {
        "id": "PANW-BP-LOG-FWD-THREAT-AUTH",
        "display_id": "PANW BP • Logging",
        "title": "Log Forwarding Profiles Send Threat and Auth Logs",
        "category": "Logging",
        "severity": "Medium",
        "framework": "PANW",
        "section": "Best Practice - Logging",
        "cis_level": 1,
        "recommendation": (
            "Configure log forwarding profiles to send threat and authentication logs."
        ),
        "check": check_log_forwarding_threat_auth,
    },
    {
        "id": "STIG-PANW-NM-000016",
        "display_id": "STIG PANW-NM-000016",
        "title": "DoD Notice and Consent Banner Configured",
        "category": "Administrative Access",
        "severity": "Low",
        "framework": "STIG",
        "section": "STIG Administrative Access",
        "cis_level": 0,
        "recommendation": (
            "Configure the DoD-approved Notice and Consent banner on login."
        ),
        "check": check_login_banner_dod,
        "stig_ids": ["PANW-NM-000016"],
    },
    {
        "id": "STIG-PANW-NM-000048",
        "display_id": "STIG PANW-NM-000048",
        "title": "Only One Local Account for Last Resort",
        "category": "Administrative Access",
        "severity": "Medium",
        "framework": "STIG",
        "section": "STIG Administrative Access",
        "cis_level": 0,
        "recommendation": (
            "Limit local accounts to a single emergency account of last resort."
        ),
        "check": check_only_one_local_admin,
        "stig_ids": ["PANW-NM-000048"],
    },
    {
        "id": "STIG-PANW-NM-000015",
        "display_id": "STIG PANW-NM-000015",
        "title": "Failed Logon Attempts Limited to 3",
        "category": "Authentication",
        "severity": "Medium",
        "framework": "STIG",
        "section": "STIG Authentication",
        "cis_level": 0,
        "recommendation": "Set admin lockout failed attempts to 3.",
        "check": check_admin_lockout_failed_attempts_3,
        "stig_ids": ["PANW-NM-000015"],
    },
    {
        "id": "STIG-PANW-NM-000053",
        "display_id": "STIG PANW-NM-000053",
        "title": "Minimum Password Length >= 15",
        "category": "Password Requirements",
        "severity": "Medium",
        "framework": "STIG",
        "section": "STIG Password Requirements",
        "cis_level": 0,
        "recommendation": "Set minimum password length to 15 or more.",
        "check": check_password_min_length_15,
        "stig_ids": ["PANW-NM-000053"],
    },
    {
        "id": "STIG-PANW-NM-000059",
        "display_id": "STIG PANW-NM-000059",
        "title": "New Password Differs by >= 8 Characters",
        "category": "Password Requirements",
        "severity": "Medium",
        "framework": "STIG",
        "section": "STIG Password Requirements",
        "cis_level": 0,
        "recommendation": (
            "Require new passwords to differ by at least 8 characters."
        ),
        "check": check_password_differs_8,
        "stig_ids": ["PANW-NM-000059"],
    },
    {
        "id": "STIG-PANW-NM-000101",
        "display_id": "STIG PANW-NM-000101",
        "title": "Timezone Set to UTC or GMT",
        "category": "Time Settings",
        "severity": "Medium",
        "framework": "STIG",
        "section": "STIG Time Settings",
        "cis_level": 0,
        "recommendation": "Set timezone to UTC or GMT.",
        "check": check_timezone_utc_gmt,
        "stig_ids": ["PANW-NM-000101"],
    },
    {
        "id": "STIG-PANW-NM-000118",
        "display_id": "STIG PANW-NM-000118",
        "title": "SNMP v1/v2 Disabled",
        "category": "SNMP",
        "severity": "High",
        "framework": "STIG",
        "section": "STIG SNMP",
        "cis_level": 0,
        "recommendation": "Disable SNMP v1/v2 and use SNMP v3 only.",
        "check": check_snmp_v1_v2_disabled,
        "stig_ids": ["PANW-NM-000118"],
    },
    {
        "id": "STIG-PANW-NM-000144",
        "display_id": "STIG PANW-NM-000144",
        "title": "Log on High Data Plane CPU Load Enabled",
        "category": "Logging",
        "severity": "Medium",
        "framework": "STIG",
        "section": "STIG Logging",
        "cis_level": 0,
        "recommendation": "Enable logging on high data plane load.",
        "check": check_log_high_dp_load_enabled,
        "stig_ids": ["PANW-NM-000144"],
    },
    {
        "id": "STIG-PANW-NM-000097",
        "display_id": "STIG PANW-NM-000097",
        "title": "Alarm Generation Enabled",
        "category": "Logging",
        "severity": "Low",
        "framework": "STIG",
        "section": "STIG Logging",
        "cis_level": 0,
        "recommendation": "Enable system alarm generation and notifications.",
        "check": check_alarms_enabled,
        "stig_ids": ["PANW-NM-000097"],
    },
    {
        "id": "STIG-PANW-NM-000145",
        "display_id": "STIG PANW-NM-000145",
        "title": "NTP Authentication Enabled",
        "category": "Time Settings",
        "severity": "Medium",
        "framework": "STIG",
        "section": "STIG Time Settings",
        "cis_level": 0,
        "recommendation": "Enable NTP authentication using symmetric key or autokey.",
        "check": check_ntp_authentication_enabled,
        "stig_ids": ["PANW-NM-000145"],
    },
    {
        "id": "STIG-PANW-NM-000029",
        "display_id": "STIG PANW-NM-000029",
        "title": "Syslog Includes Hostname or FQDN",
        "category": "Logging",
        "severity": "Low",
        "framework": "STIG",
        "section": "STIG Logging",
        "cis_level": 0,
        "recommendation": (
            "Configure syslog to include hostname or FQDN for event sources."
        ),
        "check": check_syslog_hostname_or_fqdn,
        "stig_ids": ["PANW-NM-000029"],
    },
    {
        "id": "STIG-PANW-NM-000046",
        "display_id": "STIG PANW-NM-000046",
        "title": "Unnecessary Services Disabled",
        "category": "Service Configuration",
        "severity": "Medium",
        "framework": "STIG",
        "section": "STIG Service Configuration",
        "cis_level": 0,
        "recommendation": "Disable services and protocols not required by policy.",
        "manual": True,
        "check": check_manual,
        "stig_ids": ["PANW-NM-000046"],
    },
    {
        "id": "STIG-PANW-NM-000051",
        "display_id": "STIG PANW-NM-000051",
        "title": "Replay-Resistant Authentication for Privileged Access",
        "category": "Authentication",
        "severity": "Medium",
        "framework": "STIG",
        "section": "STIG Authentication",
        "cis_level": 0,
        "recommendation": "Use replay-resistant authentication mechanisms.",
        "manual": True,
        "check": check_manual,
        "stig_ids": ["PANW-NM-000051"],
    },
    {
        "id": "STIG-PANW-NM-000075",
        "display_id": "STIG PANW-NM-000075",
        "title": "Separate Administrator Roles",
        "category": "Administrative Access",
        "severity": "Medium",
        "framework": "STIG",
        "section": "STIG Administrative Access",
        "cis_level": 0,
        "recommendation": "Ensure separation of duties for admin roles.",
        "manual": True,
        "check": check_manual,
        "stig_ids": ["PANW-NM-000075"],
    },
    {
        "id": "STIG-PANW-NM-000092",
        "display_id": "STIG PANW-NM-000092",
        "title": "Account Lockout Requires Admin Release",
        "category": "Authentication",
        "severity": "Medium",
        "framework": "STIG",
        "section": "STIG Authentication",
        "cis_level": 0,
        "recommendation": "Require admin release for locked accounts.",
        "check": check_admin_lockout_requires_release,
        "stig_ids": ["PANW-NM-000092"],
    },
    {
        "id": "STIG-PANW-NM-000096",
        "display_id": "STIG PANW-NM-000096",
        "title": "Audit Storage Alarms at 75% Capacity",
        "category": "Logging",
        "severity": "Low",
        "framework": "STIG",
        "section": "STIG Logging",
        "cis_level": 0,
        "recommendation": "Set audit log DB alarms to 75% capacity.",
        "check": check_audit_storage_alarms_75,
        "stig_ids": ["PANW-NM-000096"],
        "stig_level": 1,
    },
    {
        "id": "STIG-PANW-NM-000110",
        "display_id": "STIG PANW-NM-000110",
        "title": "PIV Credentials Accepted and Verified",
        "category": "Authentication",
        "severity": "Medium",
        "framework": "STIG",
        "section": "STIG Authentication",
        "cis_level": 0,
        "recommendation": "Import DoD CA certs and configure certificate profiles.",
        "manual": True,
        "check": check_manual,
        "stig_ids": ["PANW-NM-000110"],
    },
    {
        "id": "STIG-PANW-NM-000131",
        "display_id": "STIG PANW-NM-000131",
        "title": "Threat Alerts to Security Personnel",
        "category": "Monitoring",
        "severity": "Medium",
        "framework": "STIG",
        "section": "STIG Monitoring",
        "cis_level": 0,
        "recommendation": "Configure automated alerts for authoritative threat intel.",
        "manual": True,
        "check": check_manual,
        "stig_ids": ["PANW-NM-000131"],
    },
    {
        "id": "STIG-PANW-NM-000136",
        "display_id": "STIG PANW-NM-000136",
        "title": "Centrally Managed Authentication Servers Used",
        "category": "Authentication",
        "severity": "Medium",
        "framework": "STIG",
        "section": "STIG Authentication",
        "cis_level": 0,
        "recommendation": "Use centralized authentication servers for admins.",
        "manual": True,
        "check": check_manual,
        "stig_ids": ["PANW-NM-000136"],
    },
    {
        "id": "STIG-PANW-NM-000141",
        "display_id": "STIG PANW-NM-000141",
        "title": "DoD-Approved PKI Certificates Used",
        "category": "PKI",
        "severity": "Medium",
        "framework": "STIG",
        "section": "STIG PKI",
        "cis_level": 0,
        "recommendation": "Use DoD-approved PKI certificates for device certs.",
        "manual": True,
        "check": check_manual,
        "stig_ids": ["PANW-NM-000141"],
    },
    {
        "id": "STIG-PANW-NM-000143",
        "display_id": "STIG PANW-NM-000143",
        "title": "Default Admin Password Not Used",
        "category": "Authentication",
        "severity": "High",
        "framework": "STIG",
        "section": "STIG Authentication",
        "cis_level": 0,
        "recommendation": "Ensure the default admin password is changed.",
        "manual": True,
        "check": check_manual,
        "stig_ids": ["PANW-NM-000143"],
    },
    {
        "id": "CIS-PA-1.2.3",
        "display_id": "CIS 1.2.3",
        "title": "HTTP and Telnet Disabled for Management Interface",
        "category": "Management Interface",
        "severity": "Medium",
        "framework": "CIS",
        "section": "CIS 1.2 Management Interface",
        "cis_level": 1,
        "recommendation": "Disable HTTP and Telnet on the management interface.",
        "check": check_mgmt_http_telnet_disabled,
        "stig_ids": ["PANW-NM-000061", "PANW-NM-000117"],
        "stig_level": 2,
    },
    {
        "id": "CIS-PA-1.2.4",
        "display_id": "CIS 1.2.4",
        "title": "HTTP and Telnet Disabled for All Management Profiles",
        "category": "Management Profiles",
        "severity": "Medium",
        "framework": "CIS",
        "section": "CIS 1.2 Management Interface",
        "cis_level": 1,
        "recommendation": "Disable HTTP and Telnet on all interface management profiles.",
        "check": check_mgmt_profile_http_telnet_disabled,
    },
    {
        "id": "CIS-PA-1.2.5",
        "display_id": "CIS 1.2.5",
        "title": "Valid Certificate Set for Browser-Based Admin Interface",
        "category": "Management Interface",
        "severity": "Medium",
        "framework": "CIS",
        "section": "CIS 1.2 Management Interface",
        "cis_level": 1,
        "recommendation": (
            "Configure an SSL/TLS service profile with a valid certificate for the "
            "management interface and verify certificate trust and validity."
        ),
        "check": check_mgmt_ssl_tls_certificate_set,
    },
    {
        "id": "CIS-PA-1.3.1",
        "display_id": "CIS 1.3.1",
        "title": "Minimum Password Complexity Enabled",
        "category": "Password Requirements",
        "severity": "Medium",
        "framework": "CIS",
        "section": "CIS 1.3 Password Requirements",
        "cis_level": 1,
        "recommendation": "Enable minimum password complexity for local accounts.",
        "check": check_password_complexity_enabled,
    },
    {
        "id": "CIS-PA-1.3.2",
        "display_id": "CIS 1.3.2",
        "title": "Minimum Password Length >= 12",
        "category": "Password Requirements",
        "severity": "Medium",
        "framework": "CIS",
        "section": "CIS 1.3 Password Requirements",
        "cis_level": 1,
        "recommendation": "Set minimum password length to 12 or more.",
        "check": check_password_min_length_12,
    },
    {
        "id": "CIS-PA-1.6.2",
        "display_id": "CIS 1.6.2",
        "title": "Redundant NTP Servers Configured",
        "category": "Device Services",
        "severity": "Low",
        "framework": "CIS",
        "section": "CIS 1.6 Device Services",
        "cis_level": 1,
        "recommendation": "Configure both primary and secondary NTP servers.",
        "check": check_ntp_redundant_servers,
        "stig_ids": ["PANW-NM-000098", "PANW-NM-000099", "PANW-NM-000100"],
        "stig_level": 2,
    },
    {
        "id": "CIS-PA-1.1.1.1",
        "display_id": "CIS 1.1.1.1",
        "title": "Syslog Logging Configured",
        "category": "Logging",
        "severity": "Medium",
        "framework": "CIS",
        "section": "CIS 1.1 Logging",
        "cis_level": 1,
        "recommendation": "Configure Syslog server profiles and log forwarding.",
        "check": check_syslog_configured,
        "stig_ids": ["PANW-NM-000024", "PANW-NM-000128"],
        "stig_level": 2,
    },
    {
        "id": "CIS-PA-1.1.1.2",
        "display_id": "CIS 1.1.1.2",
        "title": "SNMPv3 Traps Configured",
        "category": "Logging",
        "severity": "Medium",
        "framework": "CIS",
        "section": "CIS 1.1 Logging",
        "cis_level": 2,
        "recommendation": "Configure SNMPv3 trap profiles and log forwarding.",
        "check": check_snmpv3_traps_configured,
        "stig_ids": ["PANW-NM-000118"],
        "stig_level": 3,
    },
    {
        "id": "CIS-PA-1.1.2",
        "display_id": "CIS 1.1.2",
        "title": "Login Banner Set",
        "category": "Logging",
        "severity": "Medium",
        "framework": "CIS",
        "section": "CIS 1.1 Logging",
        "cis_level": 1,
        "recommendation": "Configure a login banner for administrator access.",
        "check": check_login_banner_set,
    },
    {
        "id": "CIS-PA-1.1.3",
        "display_id": "CIS 1.1.3",
        "title": "Enable Log on High DP Load",
        "category": "Logging",
        "severity": "Medium",
        "framework": "CIS",
        "section": "CIS 1.1 Logging",
        "cis_level": 1,
        "recommendation": "Enable logging when data plane load is high.",
        "check": check_log_high_dp_load_enabled,
    },
    {
        "id": "CIS-PA-2.1",
        "display_id": "CIS 2.1",
        "title": "IP Addresses Mapped to Usernames",
        "category": "User Identification",
        "severity": "Medium",
        "framework": "CIS",
        "section": "CIS 2 User Identification",
        "cis_level": 2,
        "recommendation": "Configure User-ID sources to map IP addresses to usernames.",
        "check": check_ip_user_mapping_configured,
    },
    {
        "id": "CIS-PA-2.2",
        "display_id": "CIS 2.2",
        "title": "WMI Probing Disabled",
        "category": "User Identification",
        "severity": "Medium",
        "framework": "CIS",
        "section": "CIS 2 User Identification",
        "cis_level": 2,
        "recommendation": "Disable WMI probing unless explicitly required.",
        "check": check_wmi_probing_disabled,
    },
    {
        "id": "CIS-PA-2.3",
        "display_id": "CIS 2.3",
        "title": "User-ID Only on Trusted Interfaces",
        "category": "User Identification",
        "severity": "Medium",
        "framework": "CIS",
        "section": "CIS 2 User Identification",
        "cis_level": 1,
        "recommendation": "Enable User-ID only on trusted internal interfaces.",
        "check": check_user_id_only_on_trusted,
    },
    {
        "id": "CIS-PA-2.4",
        "display_id": "CIS 2.4",
        "title": "User-ID Include/Exclude Networks Configured",
        "category": "User Identification",
        "severity": "Medium",
        "framework": "CIS",
        "section": "CIS 2 User Identification",
        "cis_level": 1,
        "recommendation": "Configure include/exclude networks for User-ID scope.",
        "check": check_user_id_include_exclude_configured,
    },
    {
        "id": "CIS-PA-1.4.1",
        "display_id": "CIS 1.4.1",
        "title": "Idle Timeout <= 10 Minutes for Device Management",
        "category": "Authentication Settings",
        "severity": "Medium",
        "framework": "CIS",
        "section": "CIS 1.4 Authentication Settings",
        "cis_level": 1,
        "recommendation": "Set the device management idle timeout to 10 minutes or less.",
        "check": check_idle_timeout_max_10,
        "stig_ids": ["PANW-NM-000069"],
        "stig_level": 3,
    },
    {
        "id": "CIS-PA-1.4.2",
        "display_id": "CIS 1.4.2",
        "title": "Authentication Profile Failed Attempts and Lockout Time Configured",
        "category": "Authentication Settings",
        "severity": "Medium",
        "framework": "CIS",
        "section": "CIS 1.4 Authentication Settings",
        "cis_level": 1,
        "recommendation": "Configure failed attempts and lockout time in authentication profiles.",
        "check": check_auth_profile_lockout_configured,
    },
    {
        "id": "CIS-PA-1.5.1",
        "display_id": "CIS 1.5.1",
        "title": "SNMP Polling Uses v3",
        "category": "SNMP Polling",
        "severity": "Medium",
        "framework": "CIS",
        "section": "CIS 1.5 SNMP Polling",
        "cis_level": 1,
        "recommendation": "Configure SNMP polling to use version 3 only.",
        "check": check_snmp_polling_v3,
        "stig_ids": ["PANW-NM-000118"],
        "stig_level": 3,
    },
    {
        "id": "CIS-PA-1.6.1",
        "display_id": "CIS 1.6.1",
        "title": "Verify Update Server Identity Enabled",
        "category": "Device Services",
        "severity": "Medium",
        "framework": "CIS",
        "section": "CIS 1.6 Device Services",
        "cis_level": 1,
        "recommendation": "Enable verification of update server identity.",
        "check": check_verify_update_server_identity,
    },
    {
        "id": "CIS-PA-1.3.3",
        "display_id": "CIS 1.3.3",
        "title": "Minimum Uppercase Letters >= 1",
        "category": "Password Requirements",
        "severity": "Medium",
        "framework": "CIS",
        "section": "CIS 1.3 Password Requirements",
        "cis_level": 1,
        "recommendation": "Set minimum uppercase letters to 1 or more.",
        "check": check_password_min_uppercase_1,
        "stig_ids": ["PANW-NM-000055"],
        "stig_level": 2,
    },
    {
        "id": "CIS-PA-1.3.4",
        "display_id": "CIS 1.3.4",
        "title": "Minimum Lowercase Letters >= 1",
        "category": "Password Requirements",
        "severity": "Medium",
        "framework": "CIS",
        "section": "CIS 1.3 Password Requirements",
        "cis_level": 1,
        "recommendation": "Set minimum lowercase letters to 1 or more.",
        "check": check_password_min_lowercase_1,
        "stig_ids": ["PANW-NM-000056"],
        "stig_level": 2,
    },
    {
        "id": "CIS-PA-1.3.5",
        "display_id": "CIS 1.3.5",
        "title": "Minimum Numeric Letters >= 1",
        "category": "Password Requirements",
        "severity": "Medium",
        "framework": "CIS",
        "section": "CIS 1.3 Password Requirements",
        "cis_level": 1,
        "recommendation": "Set minimum numeric letters to 1 or more.",
        "check": check_password_min_numeric_1,
        "stig_ids": ["PANW-NM-000057"],
        "stig_level": 2,
    },
    {
        "id": "CIS-PA-1.3.6",
        "display_id": "CIS 1.3.6",
        "title": "Minimum Special Characters >= 1",
        "category": "Password Requirements",
        "severity": "Medium",
        "framework": "CIS",
        "section": "CIS 1.3 Password Requirements",
        "cis_level": 1,
        "recommendation": "Set minimum special characters to 1 or more.",
        "check": check_password_min_special_1,
        "stig_ids": ["PANW-NM-000058"],
        "stig_level": 2,
    },
    {
        "id": "CIS-PA-1.3.7",
        "display_id": "CIS 1.3.7",
        "title": "Required Password Change Period <= 90 Days",
        "category": "Password Requirements",
        "severity": "Medium",
        "framework": "CIS",
        "section": "CIS 1.3 Password Requirements",
        "cis_level": 1,
        "recommendation": "Set required password change period to 90 days or less.",
        "check": check_password_change_period_max_90,
    },
    {
        "id": "CIS-PA-1.3.8",
        "display_id": "CIS 1.3.8",
        "title": "New Password Differs By Characters >= 3",
        "category": "Password Requirements",
        "severity": "Medium",
        "framework": "CIS",
        "section": "CIS 1.3 Password Requirements",
        "cis_level": 1,
        "recommendation": "Set new password differs by characters to 3 or more.",
        "check": check_password_differs_3,
    },
    {
        "id": "CIS-PA-1.3.9",
        "display_id": "CIS 1.3.9",
        "title": "Prevent Password Reuse Limit >= 24",
        "category": "Password Requirements",
        "severity": "Medium",
        "framework": "CIS",
        "section": "CIS 1.3 Password Requirements",
        "cis_level": 1,
        "recommendation": "Set prevent password reuse limit to 24 or more.",
        "check": check_password_reuse_24,
    },
    {
        "id": "CIS-PA-1.3.10",
        "display_id": "CIS 1.3.10",
        "title": "Password Profiles Do Not Exist",
        "category": "Password Requirements",
        "severity": "Medium",
        "framework": "CIS",
        "section": "CIS 1.3 Password Requirements",
        "cis_level": 1,
        "recommendation": "Remove weak password profiles or ensure stronger policies.",
        "check": check_password_profiles_absent,
        "stig_ids": ["PANW-NM-000142"],
        "stig_level": 2,
    },
    {
        "id": "CIS-PA-1.7.1",
        "display_id": "CIS 1.7.1",
        "title": "Post-Quantum Enabled on IKEv2 VPNs",
        "category": "VPN Settings",
        "severity": "Low",
        "framework": "CIS",
        "section": "CIS 1.7 VPN Settings",
        "cis_level": 1,
        "recommendation": "Review IKEv2 VPNs for PQ enablement.",
        "check": check_ikev2_post_quantum_enabled,
    },
    {
        "id": "CIS-PA-3.1",
        "display_id": "CIS 3.1",
        "title": "HA Peer Fully Synchronized",
        "category": "High Availability",
        "severity": "Medium",
        "framework": "CIS",
        "section": "CIS 3 High Availability",
        "cis_level": 1,
        "recommendation": "Configure HA2 and enable session synchronization.",
        "check": check_ha_peer_configured,
    },
    {
        "id": "CIS-PA-3.2",
        "display_id": "CIS 3.2",
        "title": "HA Link or Path Monitoring Enabled",
        "category": "High Availability",
        "severity": "Medium",
        "framework": "CIS",
        "section": "CIS 3 High Availability",
        "cis_level": 1,
        "recommendation": "Enable link monitoring and/or path monitoring.",
        "check": check_ha_link_or_path_monitoring,
    },
    {
        "id": "CIS-PA-3.3",
        "display_id": "CIS 3.3",
        "title": "Passive Link State Auto and Preemptive Disabled",
        "category": "High Availability",
        "severity": "Medium",
        "framework": "CIS",
        "section": "CIS 3 High Availability",
        "cis_level": 1,
        "recommendation": "Set passive link state to auto and disable preemptive.",
        "check": check_ha_passive_link_state_preemptive,
    },
    {
        "id": "CIS-PA-4.1",
        "display_id": "CIS 4.1",
        "title": "Antivirus Updates Hourly",
        "category": "Dynamic Updates",
        "severity": "Medium",
        "framework": "CIS",
        "section": "CIS 4 Dynamic Updates",
        "cis_level": 1,
        "recommendation": "Set antivirus updates to download and install hourly.",
        "check": check_antivirus_updates_hourly,
    },
    {
        "id": "CIS-PA-4.2",
        "display_id": "CIS 4.2",
        "title": "Applications and Threats Updates Daily or Better",
        "category": "Dynamic Updates",
        "severity": "Medium",
        "framework": "CIS",
        "section": "CIS 4 Dynamic Updates",
        "cis_level": 1,
        "recommendation": "Set applications and threats updates to daily, hourly, or every 30 minutes.",
        "check": check_threats_updates_daily_or_better,
    },
    {
        "id": "CIS-PA-5.1",
        "display_id": "CIS 5.1",
        "title": "WildFire File Size Limits Maximized",
        "category": "WildFire",
        "severity": "Medium",
        "framework": "CIS",
        "section": "CIS 5 WildFire",
        "cis_level": 1,
        "recommendation": "Set WildFire file size limits to defaults or larger.",
        "check": check_wildfire_file_size_limits,
    },
    {
        "id": "CIS-PA-5.2",
        "display_id": "CIS 5.2",
        "title": "WildFire Analysis Enabled on All Allow Rules",
        "category": "WildFire",
        "severity": "High",
        "framework": "CIS",
        "section": "CIS 5 WildFire",
        "cis_level": 1,
        "recommendation": "Apply WildFire analysis profiles to all allow rules.",
        "check": check_wildfire_analysis_on_rules,
        "scope": "rules",
    },
    {
        "id": "CIS-PA-5.3",
        "display_id": "CIS 5.3",
        "title": "Forward Decrypted Content to WildFire",
        "category": "WildFire",
        "severity": "Medium",
        "framework": "CIS",
        "section": "CIS 5 WildFire",
        "cis_level": 1,
        "recommendation": "Enable forwarding of decrypted content to WildFire.",
        "check": check_wildfire_forward_decrypted_content,
    },
    {
        "id": "CIS-PA-5.4",
        "display_id": "CIS 5.4",
        "title": "WildFire Session Information Settings Enabled",
        "category": "WildFire",
        "severity": "Medium",
        "framework": "CIS",
        "section": "CIS 5 WildFire",
        "cis_level": 1,
        "recommendation": "Enable all WildFire session information settings.",
        "check": check_wildfire_session_info_settings,
    },
    {
        "id": "CIS-PA-5.5",
        "display_id": "CIS 5.5",
        "title": "WildFire Alerts Enabled",
        "category": "WildFire",
        "severity": "Medium",
        "framework": "CIS",
        "section": "CIS 5 WildFire",
        "cis_level": 1,
        "recommendation": "Enable WildFire alerts through log forwarding.",
        "check": check_wildfire_alerts_enabled,
    },
    {
        "id": "CIS-PA-5.6",
        "display_id": "CIS 5.6",
        "title": "WildFire Updates Real-Time",
        "category": "WildFire",
        "severity": "Medium",
        "framework": "CIS",
        "section": "CIS 5 WildFire",
        "cis_level": 1,
        "recommendation": "Set WildFire updates to real-time.",
        "check": check_wildfire_update_realtime,
    },
    {
        "id": "CIS-PA-5.7",
        "display_id": "CIS 5.7",
        "title": "WildFire Public Cloud Region Set",
        "category": "WildFire",
        "severity": "Low",
        "framework": "CIS",
        "section": "CIS 5 WildFire",
        "cis_level": 2,
        "recommendation": "Set WildFire public cloud region appropriately.",
        "check": check_wildfire_public_cloud_region,
    },
    {
        "id": "CIS-PA-5.8",
        "display_id": "CIS 5.8",
        "title": "WildFire Inline Cloud Analysis Enabled",
        "category": "WildFire",
        "severity": "Low",
        "framework": "CIS",
        "section": "CIS 5 WildFire",
        "cis_level": 1,
        "recommendation": "Enable inline cloud analysis in WildFire profiles.",
        "check": check_wildfire_inline_cloud_analysis,
    },
    {
        "id": "CIS-PA-6.1",
        "display_id": "CIS 6.1",
        "title": "Antivirus Profiles Reset-Both on Decoders",
        "category": "Threat Prevention",
        "severity": "High",
        "framework": "CIS",
        "section": "CIS 6 Threat Prevention",
        "cis_level": 1,
        "recommendation": "Set antivirus decoders to reset-both (except imap/pop3).",
        "check": check_av_reset_both_decoders,
    },
    {
        "id": "CIS-PA-6.3",
        "display_id": "CIS 6.3",
        "title": "Anti-Spyware Profiles Block All Severities",
        "category": "Threat Prevention",
        "severity": "High",
        "framework": "CIS",
        "section": "CIS 6 Threat Prevention",
        "cis_level": 1,
        "recommendation": "Block critical, high, medium, and low spyware severities.",
        "check": check_spyware_blocks_all_severities,
    },
    {
        "id": "CIS-PA-6.4",
        "display_id": "CIS 6.4",
        "title": "DNS Sinkholing Configured on Anti-Spyware Profiles",
        "category": "Threat Prevention",
        "severity": "Medium",
        "framework": "CIS",
        "section": "CIS 6 Threat Prevention",
        "cis_level": 1,
        "recommendation": "Enable DNS sinkholing on spyware profiles in use.",
        "check": check_spyware_dns_sinkhole,
    },
    {
        "id": "CIS-PA-6.6",
        "display_id": "CIS 6.6",
        "title": "Vulnerability Protection Blocks Critical/High",
        "category": "Threat Prevention",
        "severity": "High",
        "framework": "CIS",
        "section": "CIS 6 Threat Prevention",
        "cis_level": 1,
        "recommendation": "Block critical and high severity vulnerabilities.",
        "check": check_vp_blocks_critical_high,
    },
    {
        "id": "CIS-PA-6.11",
        "display_id": "CIS 6.11",
        "title": "HTTP Header Logging Enabled",
        "category": "URL Filtering",
        "severity": "Medium",
        "framework": "CIS",
        "section": "CIS 6 Threat Prevention",
        "cis_level": 1,
        "recommendation": "Enable User-Agent, Referer, and X-Forwarded-For logging.",
        "check": check_url_http_header_logging,
    },
    {
        "id": "CIS-PA-6.12",
        "display_id": "CIS 6.12",
        "title": "URL Filtering Enabled on All Allow Rules",
        "category": "URL Filtering",
        "severity": "Medium",
        "framework": "CIS",
        "section": "CIS 6 Threat Prevention",
        "cis_level": 1,
        "recommendation": "Apply URL filtering profiles to all allow rules.",
        "check": check_url_filtering_on_rules,
        "scope": "rules",
    },
    {
        "id": "CIS-PA-6.9",
        "display_id": "CIS 6.9",
        "title": "URL Filtering Blocks or Overrides Risk Categories",
        "category": "URL Filtering",
        "severity": "Medium",
        "framework": "CIS",
        "section": "CIS 6 Threat Prevention",
        "cis_level": 1,
        "recommendation": (
            "Set URL Filtering categories to block or override: adult, hacking, "
            "command-and-control, copyright-infringement, extremism, malware, "
            "phishing, proxy-avoidance-and-anonymizers, and parked."
        ),
        "check": check_url_filtering_block_override_categories,
    },
    {
        "id": "CIS-PA-6.10",
        "display_id": "CIS 6.10",
        "title": "Access to Every URL is Logged",
        "category": "URL Filtering",
        "severity": "Medium",
        "framework": "CIS",
        "section": "CIS 6 Threat Prevention",
        "cis_level": 1,
        "recommendation": (
            "Ensure no URL categories are set to allow; use at least alert "
            "or stricter actions."
        ),
        "check": check_url_filtering_no_allow_categories,
    },
    {
        "id": "CIS-PA-6.15",
        "display_id": "CIS 6.15",
        "title": "Zone Protection SYN Cookies Enabled on Untrusted Zones",
        "category": "Zone Protection",
        "severity": "Medium",
        "framework": "CIS",
        "section": "CIS 6 Threat Prevention",
        "cis_level": 1,
        "recommendation": "Attach a zone protection profile with SYN cookies enabled to untrusted zones.",
        "check": check_zone_protection_syn_cookies,
    },
    {
        "id": "CIS-PA-6.16",
        "display_id": "CIS 6.16",
        "title": "Zone Protection Flood Protection Enabled on Untrusted Zones",
        "category": "Zone Protection",
        "severity": "Medium",
        "framework": "CIS",
        "section": "CIS 6 Threat Prevention",
        "cis_level": 1,
        "recommendation": "Enable tuned flood protection for all flood types on untrusted zones.",
        "check": check_zone_protection_flood_enabled,
    },
    {
        "id": "CIS-PA-6.17",
        "display_id": "CIS 6.17",
        "title": "Zone Protection Reconnaissance Protection Enabled",
        "category": "Zone Protection",
        "severity": "Medium",
        "framework": "CIS",
        "section": "CIS 6 Threat Prevention",
        "cis_level": 1,
        "recommendation": "Enable reconnaissance protection settings on zone protection profiles.",
        "check": check_zone_protection_recon_enabled,
    },
    {
        "id": "CIS-PA-6.18",
        "display_id": "CIS 6.18",
        "title": "Zone Protection Drops Specially Crafted Packets",
        "category": "Zone Protection",
        "severity": "Medium",
        "framework": "CIS",
        "section": "CIS 6 Threat Prevention",
        "cis_level": 1,
        "recommendation": "Enable drop settings for spoofed and malformed packets on zone protection profiles.",
        "check": check_zone_protection_drop_special,
    },
    {
        "id": "CIS-PA-6.22",
        "display_id": "CIS 6.22",
        "title": "Vulnerability Inline Cloud Analysis Enabled",
        "category": "Threat Prevention",
        "severity": "Low",
        "framework": "CIS",
        "section": "CIS 6 Threat Prevention",
        "cis_level": 1,
        "recommendation": "Enable inline cloud analysis on vulnerability profiles in use.",
        "check": check_vp_inline_cloud_analysis,
    },
    {
        "id": "CIS-PA-6.23",
        "display_id": "CIS 6.23",
        "title": "URL Filtering Cloud Inline Categorization Enabled",
        "category": "URL Filtering",
        "severity": "Low",
        "framework": "CIS",
        "section": "CIS 6 Threat Prevention",
        "cis_level": 1,
        "recommendation": "Enable cloud inline categorization on URL filtering profiles.",
        "check": check_url_cloud_inline_categorization,
    },
    {
        "id": "CIS-PA-6.24",
        "display_id": "CIS 6.24",
        "title": "Anti-Spyware Inline Cloud Analysis Enabled",
        "category": "Threat Prevention",
        "severity": "Low",
        "framework": "CIS",
        "section": "CIS 6 Threat Prevention",
        "cis_level": 1,
        "recommendation": "Enable inline cloud analysis on anti-spyware profiles in use.",
        "check": check_spyware_inline_cloud_analysis,
    },
    {
        "id": "CIS-PA-7.1",
        "display_id": "CIS 7.1",
        "title": "Application-Specific Policies for Untrusted to Trusted Traffic",
        "category": "Security Policy",
        "severity": "High",
        "framework": "CIS",
        "section": "CIS 7 Security Policies",
        "cis_level": 1,
        "recommendation": "Use application-specific allow rules for untrusted to trusted traffic.",
        "check": check_app_specific_untrusted_to_trusted,
        "scope": "rules",
    },
    {
        "id": "CIS-PA-7.2",
        "display_id": "CIS 7.2",
        "title": "Service Any Not Used in Allow Rules",
        "category": "Security Policy",
        "severity": "High",
        "framework": "CIS",
        "section": "CIS 7 Security Policies",
        "cis_level": 1,
        "recommendation": "Use application-default or specific services on allow rules.",
        "check": check_service_any,
        "scope": "rules",
    },
    {
        "id": "CIS-PA-7.3",
        "display_id": "CIS 7.3",
        "title": "Deny Rules for Malicious IPs Present",
        "category": "Security Policy",
        "severity": "Medium",
        "framework": "CIS",
        "section": "CIS 7 Security Policies",
        "cis_level": 1,
        "recommendation": "Create deny rules using known malicious IP EDLs.",
        "check": check_malicious_ip_deny_rules,
        "scope": "rules",
    },
    {
        "id": "CIS-PA-7.4",
        "display_id": "CIS 7.4",
        "title": "Default Security Policy Logging Enabled",
        "category": "Security Policy",
        "severity": "Low",
        "framework": "CIS",
        "section": "CIS 7 Security Policies",
        "cis_level": 1,
        "recommendation": "Enable log at session end on intrazone-default and interzone-default.",
        "check": check_default_policy_logging,
        "scope": "rules",
    },
    {
        "id": "CIS-PA-8.1",
        "display_id": "CIS 8.1",
        "title": "SSL Forward Proxy Policy Configured for Internet Traffic",
        "category": "Decryption",
        "severity": "Medium",
        "framework": "CIS",
        "section": "CIS 8 Decryption",
        "cis_level": 1,
        "recommendation": "Configure SSL Forward Proxy policies for Internet-bound traffic.",
        "manual": True,
        "check": check_manual,
    },
    {
        "id": "CIS-PA-8.2",
        "display_id": "CIS 8.2",
        "title": "SSL Inbound Inspection Required for Untrusted SSL/TLS Servers",
        "category": "Decryption",
        "severity": "Medium",
        "framework": "CIS",
        "section": "CIS 8 Decryption",
        "cis_level": 1,
        "recommendation": "Require SSL Inbound Inspection for untrusted traffic to SSL/TLS servers.",
        "manual": True,
        "check": check_manual,
    },
    {
        "id": "CIS-PA-8.3",
        "display_id": "CIS 8.3",
        "title": "Certificate Used for Decryption is Trusted",
        "category": "Decryption",
        "severity": "Medium",
        "framework": "CIS",
        "section": "CIS 8 Decryption",
        "cis_level": 1,
        "recommendation": "Ensure the decryption certificate is valid and trusted.",
        "manual": True,
        "check": check_manual,
    },
]
